python main.py abaumannii
python main.py calbicans
python main.py campylobacter
python main.py ecoli
python main.py efaecium
python main.py enterobacter
python main.py hpylori
python main.py kpneumoniae
python main.py mtuberculosis
python main.py ngonorrhoeae
python main.py paeruginosa
python main.py pfalciparum
python main.py saureus
python main.py smansoni
python main.py spneumoniae